version: '3'

services:
  test_db:
    image: mysql
    environment:
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - mysql_db:/var/lib/mysql
    ports:
      - "3306:3306"
volumes:
  mysql_db: